Repository Blocship/star_book, pull requests merged in 2023-02, with the labels that each got.

#293 UI/create calendar
  lib/main.dart
  lib/presentation/screen/calendar/calendar_view.dart
  lib/presentation/screen/calendar/custom_calendar.dart
  lib/presentation/screen/calendar/custom_calendar_card.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/calendar/year_title.dart
  lib/presentation/utils/calendar.dart
  lib/theme/ultramarine_light.dart
  lib/widgets/gradient_scaffold.dart
Labels: in progress, In review

#295 UI/design buttons
  lib/presentation/shared/elevated_buttons.dart
  lib/theme/base_theme.dart
  lib/theme/styling/filled_button_style.dart
  lib/theme/ultramarine_light.dart
Labels: In review

#300 UI/create floating action buttons
  assets/icons/calendar_add_on.png
  lib/floating_action_button.dart
  lib/theme/base_theme.dart
  lib/theme/styling/floating_action_button_style.dart
  lib/theme/ultramarine_light.dart
  pubspec.yaml
Labels: In review

#312 UI/padding theme
  lib/presentation/utils/padding_style.dart
  lib/theme/ultramarine_light.dart
Labels: In review

#314 UI Setting Tile
  lib/presentation/shared/tile.dart
Labels: In review

#315 UI Setting Screen
  assets/icons/blocship_logo.png
  assets/icons/ux_logo.png
  lib/presentation/screen/setting_screen.dart
  lib/presentation/shared/tile.dart
  lib/theme/ultramarine_light.dart
Labels: In review

#322 UI Dialog Box
  assets/icons/stop.png
  lib/presentation/shared/dialog_box.dart
  lib/presentation/shared/elevated_buttons.dart
  lib/theme/ultramarine_light.dart
Labels: In review

#316 UI Splash Screen
  assets/icons/splash_screen_logo.png
  lib/presentation/screen/splash_screen.dart
Labels: In review

#329 UI/stats widget
  assets/icons/crown.png
  assets/icons/fire.png
  lib/presentation/shared/stats_widget.dart
Labels: In review

#326 UI/mood tile
  lib/presentation/shared/mood_tile.dart
Labels: In review

#327 UI/mood picker screen
  lib/presentation/screen/mood_picker_screen.dart
Labels: In review

#311 ui/TextFormField
  lib/main.dart
  lib/presentation/shared/text_field.dart
  lib/theme/base_theme.dart
  lib/theme/styling/gradient_scaffold_style.dart
  lib/theme/styling/theme_color_style.dart
  lib/theme/ultramarine_light.dart
Labels: help wanted

#323 UI Intro Screen
  assets/images/intro_image.png
  lib/presentation/screen/intro_screen.dart
  lib/presentation/shared/text_field.dart
  lib/theme/ultramarine_light.dart
  lib/widgets/gradient_scaffold.dart
  pubspec.yaml
Labels: In review

#317 UI Bottom Navigation Bar
  assets/icons/account_circle.png
  assets/icons/home_outlined.png
  lib/presentation/screen/main_screen.dart
  lib/presentation/shared/custom_bottom_nav_bar.dart
  lib/widgets/gradient_scaffold.dart
  pubspec.lock
Labels: In review

#331 UI App Bar
  assets/icons/shooting_star.png
  lib/presentation/shared/app_bar.dart
Labels: In review

#313 UI/date picker
  lib/presentation/utils/calendar.dart
  lib/widgets/date_picker.dart
  pubspec.lock
  pubspec.yaml
Labels: In review

#338 UI DoughnutChartWidget
  lib/presentation/shared/doughnut_chart_widget.dart
  lib/theme/base_theme.dart
  lib/theme/styling/doughnut_chart_style.dart
  lib/theme/ultramarine_light.dart
  pubspec.lock
  pubspec.yaml
Labels: In review

#335 UI/doughnut chart
  lib/theme/ultramarine_light.dart
  lib/widgets/doughnut_chart.dart
  pubspec.yaml
Labels: In review

#341 UI Year Screen
  lib/presentation/screen/calendar/calendar_view.dart
  lib/presentation/screen/calendar/custom_calendar.dart
  lib/presentation/screen/year_screen.dart
  lib/presentation/shared/app_bar.dart
  pubspec.lock
Labels: In review

#345 UI Home Screen
  lib/floating_action_button.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/home_screen.dart
  lib/widgets/gradient_scaffold.dart
  pubspec.yaml
Labels: In review

#347 UI Date Picker Screen
  lib/floating_action_button.dart
  lib/presentation/screen/date_picker_screen.dart
  lib/widgets/date_picker.dart
Labels: In review

#349 UI/analytics screen
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/analytics_screens/monthly_analytics.dart
  lib/presentation/screen/analytics_screens/weekly_analytics.dart
  lib/widgets/doughnut_chart.dart
Labels: In review

#358 UI Add Home Screen and Profile Screen to Nav Bar
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/main_screen.dart
Labels: In review

#360 Feature Go Router
  lib/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: In review

#352 UI Journal Detail Screen
  lib/presentation/screen/journal_detail_screen.dart
  lib/theme/ultramarine_light.dart
Labels: In review

#355 UI Journal Edit Screen
  lib/presentation/screen/journal_edit_screen.dart
  lib/presentation/shared/text_field.dart
Labels: In review

#363 Feature/add navigation
  lib/main.dart
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/calendar/custom_calendar_card.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/date_picker_screen.dart
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_detail_screen.dart
  lib/presentation/screen/journal_edit_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/license_agreement_screen.dart
  lib/presentation/screen/mood_picker_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/screen/setting_screen.dart
  lib/presentation/screen/splash_screen.dart
  lib/presentation/screen/year_screen.dart
  lib/presentation/shared/dialog_box.dart
  lib/presentation/utils/extension.dart
  lib/presentation/utils/month_details.dart
  lib/routes/app_router_name.dart
  lib/routes/routes.dart
  pubspec.yaml
Labels: in progress

#371 Feature Navigation Bug.
  lib/presentation/screen/calendar/month_days.dart
Labels: In review

#368 UI/QA feed back
  lib/main.dart
  lib/presentation/screen/analytics_screens/weekly_analytics.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_edit_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/shared/app_bar.dart
  lib/presentation/shared/custom_bottom_nav_bar.dart
  lib/presentation/shared/doughnut_chart_widget.dart
  lib/presentation/shared/elevated_buttons.dart
  lib/presentation/shared/stats_widget.dart
  lib/presentation/shared/text_field.dart
  lib/theme/styling/theme_color_style.dart
  lib/theme/ultramarine_light.dart
  lib/widgets/doughnut_chart.dart
  pubspec.lock
Labels: In review

#374 Feature File Structure
  lib/main.dart
  lib/presentation/routes/app_router_name.dart
  lib/presentation/routes/routes.dart
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/analytics_screens/monthly_analytics.dart
  lib/presentation/screen/analytics_screens/weekly_analytics.dart
  lib/presentation/screen/calendar/custom_calendar_card.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/date_picker_screen.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_detail_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/screen/license_agreement_screen.dart
  lib/presentation/screen/main_screen.dart
  lib/presentation/screen/mood_picker_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/screen/setting_screen.dart
  lib/presentation/screen/splash_screen.dart
  lib/presentation/screen/year_screen.dart
  lib/presentation/service/cache_client.dart
  lib/presentation/service/logger.dart
  lib/presentation/service/navigator.dart
  lib/presentation/shared/app_bar.dart
  lib/presentation/shared/custom_bottom_nav_bar.dart
  lib/presentation/shared/doughnut_chart_widget.dart
  lib/presentation/shared/elevated_buttons.dart
  lib/presentation/shared/stats_widget.dart
  lib/presentation/shared/text_field.dart
  lib/presentation/theme/base_theme.dart
  lib/presentation/theme/styling/doughnut_chart_style.dart
  lib/presentation/theme/styling/filled_button_style.dart
  lib/presentation/theme/styling/floating_action_button_style.dart
  lib/presentation/theme/styling/gradient_scaffold_style.dart
  lib/presentation/theme/styling/theme_color_style.dart
  lib/presentation/theme/ultramarine_light.dart
  lib/presentation/widgets/date_picker.dart
  lib/presentation/widgets/doughnut_chart.dart
  lib/presentation/widgets/floating_action_button.dart
  lib/presentation/widgets/gradient_scaffold.dart
Labels: In review

#379 multiline functionality added
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/shared/text_field.dart
Labels: In review

#376 UI Bug Render Overflow in Bottom Nav Bar.
  lib/presentation/screen/main_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/shared/bottom_nav_bar.dart
  lib/presentation/shared/custom_bottom_nav_bar.dart
  lib/presentation/widgets/gradient_scaffold.dart
Labels: In review

#380 UI Refactor App Bar
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/date_picker_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_detail_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/screen/mood_picker_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/screen/setting_screen.dart
  lib/presentation/screen/year_screen.dart
  lib/presentation/shared/app_bar.dart
Labels: In review

#381 UI Build Context Extension
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/analytics_screens/monthly_analytics.dart
  lib/presentation/screen/analytics_screens/weekly_analytics.dart
  lib/presentation/screen/calendar/calendar_view.dart
  lib/presentation/screen/calendar/custom_calendar_card.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/calendar/year_title.dart
  lib/presentation/screen/date_picker_screen.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_detail_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/screen/license_agreement_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/screen/setting_screen.dart
  lib/presentation/screen/splash_screen.dart
  lib/presentation/shared/app_bar.dart
  lib/presentation/shared/bottom_nav_bar.dart
  lib/presentation/shared/dialog_box.dart
  lib/presentation/shared/doughnut_chart_widget.dart
  lib/presentation/shared/elevated_buttons.dart
  lib/presentation/shared/mood_tile.dart
  lib/presentation/shared/stats_widget.dart
  lib/presentation/shared/text_field.dart
  lib/presentation/shared/tile.dart
  lib/presentation/utils/extension.dart
  lib/presentation/widgets/date_picker.dart
  lib/presentation/widgets/doughnut_chart.dart
  lib/presentation/widgets/floating_action_button.dart
  lib/presentation/widgets/gradient_scaffold.dart
Labels: In review

#383 UI/app icon
  android/app/src/main/res/appstore.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/playstore.png
  assets/icon.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
  pubspec.yaml
Labels: In review

#384 UI Refactor Screens
  lib/presentation/screen/analytics_screens/analytics_tab_bar_view.dart
  lib/presentation/screen/calendar/month_days.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_detail_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/screen/profile_screen.dart
  lib/presentation/shared/app_bar.dart
  lib/presentation/shared/stats_widget.dart
  lib/presentation/shared/text_field.dart
Labels: In review

#386 UI Refactor Spacing
  lib/presentation/screen/date_picker_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/screen/setting_screen.dart
Labels: In review

#390 fixes 389 migration to latest version
  ios/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
Labels: In review

#392 Feature Implement Form Builder
  lib/cubits/cubit_state/cubit_state.dart
  lib/cubits/cubit_state/cubit_state.freezed.dart
  lib/cubits/journal_cubit.dart
  lib/presentation/routes/routes.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/screen/journal_screens/journal_create_screen.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
  lib/presentation/shared/form_models/jounral_form_model.dart
  lib/presentation/shared/form_validator.dart
  lib/presentation/shared/text_field.dart
  pubspec.lock
  pubspec.yaml
Labels: In review

#396 Feature/journal detail cubit
  lib/cubits/journal_cubit.dart
  lib/cubits/journal_detail_cubit.dart
  lib/cubits/journal_state.dart
  lib/cubits/journal_state.freezed.dart
  lib/presentation/shared/form_models/jounral_form_model.dart
Labels: In review

#406 Feature Analytics Screen Cubit
  lib/cubits/analytiics_screen_cubit.dart
Labels: In review

#402 Feature Intro Screen Cubit
  lib/cubits/intro_screen_cubit.dart
Labels: In review

#400 Feature Journal Create Cubit
  lib/cubits/journal_create_cubit.dart
Labels: In review

#398 Feature/journal edit cubit
  lib/cubits/journal_edit_cubit.dart
Labels: In review

#404 Feature Profile Screen Cubit
  lib/cubits/profile_screen_cubit.dart
Labels: In review

#408 Feature Home Screen Cubit
  lib/cubits/home_screen_cubit.dart
Labels: In review

#411 Feature Intro Screen Cubit Implementation
  lib/cubits/intro_screen_cubit.dart
  lib/presentation/screen/intro_screen.dart
  lib/presentation/shared/loader.dart
Labels: In review

#413 Feature Profile Screen Cubit Implementation.
  lib/presentation/screen/profile_screen.dart
Labels: In review

#420 Feature Journal Detail Screen Cubit Implementation.
  lib/presentation/screen/journal_screens/journal_detail_screen.dart
Labels: In review

#421 Feature Journal Create Screen Cubit Implementation.
  lib/presentation/screen/journal_screens/journal_create_screen.dart
Labels: In review

#424 Feature Journal Edit Screen Cubit Implementation
  lib/cubits/journal_edit_cubit.dart
  lib/presentation/screen/journal_screens/journal_edit_screen.dart
Labels: In review
